[package]
name = "katana-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Crawling engines (Standard, Hybrid, Headless) and execution runtime for Katana"

[dependencies]
katana-core = { workspace = true }
katana-similarity = { workspace = true }
katana-parser = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
md-5 = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
lru = { workspace = true }
lazy_static = { workspace = true }
regex = { workspace = true }
sha2 = { workspace = true }
which = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
governor = { workspace = true }
futures = { workspace = true }
tokio-tungstenite = { workspace = true }
rustls = { workspace = true }
tokio-rustls = { workspace = true }
x509-parser = { workspace = true }
