use std::collections::HashMap;

/// Global crawler configuration options.
#[derive(Debug, Clone)]
pub struct Options {
    pub urls: Vec<String>,
    pub max_depth: usize,
    pub crawl_duration: Option<u64>,
    pub concurrency: usize,
    pub parallelism: usize,
    pub delay: u64,
    pub rate_limit: usize,
    pub rate_limit_minute: usize,
    pub headless: bool,
    pub headless_hybrid: bool,
    pub system_chrome: bool,
    pub chrome_data_dir: Option<String>,
    pub chrome_ws_url: Option<String>,
    pub scrape_js: bool,
    pub scrape_jsluice: bool,
    pub form_extraction: bool,
    pub automatic_form_fill: bool,
    pub scope: Vec<String>,
    pub out_of_scope: Vec<String>,
    pub field_scope: String,
    pub no_scope: bool,
    pub display_out_scope: bool,
    pub ignore_query_params: bool,
    pub filter_similar: bool,
    pub filter_similar_threshold: usize,
    pub max_domain_pages: usize,
    pub path_climb: bool,
    pub custom_headers: HashMap<String, String>,
    pub proxy: Option<String>,
    pub disable_redirects: bool,
    pub body_read_size: usize,
    pub retries: usize,
    pub timeout: u64,
    pub user_agent: Option<String>,
    pub tls_impersonate: bool,
    pub tls_preset: Option<String>,
    pub tls_data: bool,
    pub omit_raw: bool,
    pub omit_body: bool,
    pub match_regex: Vec<String>,
    pub filter_regex: Vec<String>,
    pub captcha_solver_provider: Option<String>,
    pub captcha_solver_api_key: Option<String>,
    pub auth_credentials: Option<String>,
    pub scan_secrets: bool,
    pub output_file: Option<String>,
    pub store_response: bool,
    pub store_response_dir: Option<String>,
    pub custom_fields_config: Option<String>,
    pub fields: Option<Vec<String>>,
    pub raw_request_file: Option<String>,
    pub resume_file: Option<String>,
    pub extension_match: Vec<String>,
    pub extension_filter: Vec<String>,
    pub no_extension_filter: bool,
    pub exclude: Vec<String>,
    pub exclude_private_ips: bool,
}

impl Default for Options {
    fn default() -> Self {
        Self {
            urls: Vec::new(),
            max_depth: 3,
            crawl_duration: None,
            concurrency: 10,
            parallelism: 10,
            delay: 0,
            rate_limit: 150,
            rate_limit_minute: 0,
            headless: false,
            headless_hybrid: false,
            system_chrome: false,
            chrome_data_dir: None,
            chrome_ws_url: None,
            scrape_js: false,
            scrape_jsluice: false,
            form_extraction: false,
            automatic_form_fill: false,
            scope: Vec::new(),
            out_of_scope: Vec::new(),
            field_scope: "rdn".to_string(),
            no_scope: false,
            display_out_scope: false,
            ignore_query_params: false,
            filter_similar: false,
            filter_similar_threshold: 10,
            max_domain_pages: 0,
            path_climb: false,
            custom_headers: HashMap::new(),
            proxy: None,
            disable_redirects: false,
            body_read_size: 4 * 1024 * 1024, // 4 MiB
            retries: 1,
            timeout: 10,
            user_agent: None,
            tls_impersonate: false,
            tls_preset: None,
            tls_data: false,
            omit_raw: false,
            omit_body: false,
            match_regex: Vec::new(),
            filter_regex: Vec::new(),
            captcha_solver_provider: None,
            captcha_solver_api_key: None,
            auth_credentials: None,
            scan_secrets: false,
            output_file: None,
            store_response: false,
            store_response_dir: None,
            custom_fields_config: None,
            fields: None,
            raw_request_file: None,
            resume_file: None,
            extension_match: Vec::new(),
            extension_filter: Vec::new(),
            no_extension_filter: false,
            exclude: Vec::new(),
            exclude_private_ips: false,
        }
    }
}

/// Runtime assembly of components derived from Options.
#[derive(Debug, Clone, Default)]
pub struct CrawlerOptions {
    pub options: Options,
}
